language: python

python: 3.4

sudo: false

install:
  - npm install
  - pip install jsonchecker

script:
  # JSON Lint:
  - grunt
  # Check for duplicate values:
  - jsonchecker data --values --quiet
